In [1]:
import zipfile

zip_path = "/content/human_activity.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    print(z.namelist()[:30])

['UCI HAR Dataset.names', 'UCI HAR Dataset.zip']

In [2]:
with zipfile.ZipFile("/content/human_activity.zip", "r") as z:
    z.extract("UCI HAR Dataset.zip", "/content/")

In [3]:
with zipfile.ZipFile("/content/UCI HAR Dataset.zip", "r") as z:
    z.extractall("/content/")

In [9]:


import pandas as pd

x = pd.read_csv(
    "/content/UCI HAR Dataset/train/X_train.txt",
    sep=r"\s+",
    header=None
)

y = pd.read_csv(
    "/content/UCI HAR Dataset/train/y_train.txt",
    sep=r"\s+",
    header=None
)

In [18]:
from sklearn.model_selection import train_test_split

In [10]:
x.head()

,0,1,2,3,4,5,6,7,8,9,...,551,552,553,554,555,556,557,558,559,560
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,0.404573,-0.117290,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,0.087753,-0.351471,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892

In [11]:
y.head()

   0
0  5
1  5
2  5
3  5
4  5

In [12]:
x.shape

(7352, 561)

In [13]:
y.shape

(7352, 1)

In [14]:
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=45)

In [15]:
x_train.shape

(5881, 561)

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [41]:
knn = KNeighborsClassifier(n_neighbors = 50)

In [42]:
knn.fit(x_train , y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=50)

In [43]:
y_predict = knn.predict(x_test)

In [44]:
knn.score(x_test,y_test)

0.9503738953093134

In [45]:
cm = confusion_matrix(y_test, y_predict)
print(cm)

[[249   1   3   0   0   0]
 [  2 230   1   0   0   0]
 [  4   4 200   0   0   0]
 [  0   0   0 190  40   1]
 [  0   0   0  14 228   0]
 [  0   2   0   1   0 301]]

In [46]:
cr= classification_report(y_test, y_predict)
print(cr)

              precision    recall  f1-score   support

           1       0.98      0.98      0.98       253
           2       0.97      0.99      0.98       233
           3       0.98      0.96      0.97       208
           4       0.93      0.82      0.87       231
           5       0.85      0.94      0.89       242
           6       1.00      0.99      0.99       304

    accuracy                           0.95      1471
   macro avg       0.95      0.95      0.95      1471
weighted avg       0.95      0.95      0.95      1471

In [33]:
knn1 = KNeighborsClassifier(n_neighbors = 3)

In [34]:
knn1.fit(x_train, y_train)
y1_predict = knn1.predict(x_test)

/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [35]:
knn.score(x_test, y_test)

0.972807613868117

In [47]:
cm1 = confusion_matrix(y_test, y1_predict)
print(cm1)

[[253   0   0   0   0   0]
 [  0 233   0   0   0   0]
 [  1   1 206   0   0   0]
 [  0   0   0 209  22   0]
 [  0   0   0  16 226   0]
 [  0   0   0   1   0 303]]

In [48]:
cr1 = classification_report(y_test, y1_predict)
print(cr1)

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       253
           2       1.00      1.00      1.00       233
           3       1.00      0.99      1.00       208
           4       0.92      0.90      0.91       231
           5       0.91      0.93      0.92       242
           6       1.00      1.00      1.00       304

    accuracy                           0.97      1471
   macro avg       0.97      0.97      0.97      1471
weighted avg       0.97      0.97      0.97      1471